---
micronaut:
    application:
        name: micronaut-sandbox
                
#Uncomment to set server port
#    server:
#        port: 8080

---
datasources.default: {}
---
micronaut:
    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true